Last login: Mon Feb  8 20:54:07 on ttys003
Hackintosh:~ valtteri$ cd /Users/valtteri/OneDrive\ -\ TUNI.fi/Kurssit/Code/5G00ET61-3003\ IoT\ ja\ Web-ohjelmointi/GitRepos/valtteri.huuskonen/viikkoharkat/viikko4/weather-app 
Hackintosh:weather-app valtteri$ pwd
/Users/valtteri/OneDrive - TUNI.fi/Kurssit/Code/5G00ET61-3003 IoT ja Web-ohjelmointi/GitRepos/valtteri.huuskonen/viikkoharkat/viikko4/weather-app
Hackintosh:weather-app valtteri$ cd ..
Hackintosh:viikko4 valtteri$ cd ..
Hackintosh:viikkoharkat valtteri$ 














Hackintosh:viikkoharkat valtteri$ ls
viikko3	viikko4
Hackintosh:viikkoharkat valtteri$ cd viikko4/
Hackintosh:viikko4 valtteri$ ls
weather-app
Hackintosh:viikko4 valtteri$ 


















Hackintosh:viikko4 valtteri$ cd weather-app/
Hackintosh:weather-app valtteri$ ls
backend			docker-compose.yml
Hackintosh:weather-app valtteri$ 




















Hackintosh:weather-app valtteri$ ls
backend			docker-compose.yml
Hackintosh:weather-app valtteri$ 
Hackintosh:weather-app valtteri$ 
Hackintosh:weather-app valtteri$ 
Hackintosh:weather-app valtteri$ 


















Hackintosh:weather-app valtteri$ docker-compose up -d
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "site-packages/docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 727, in urlopen
  File "site-packages/urllib3/util/retry.py", line 403, in increment
  File "site-packages/urllib3/packages/six.py", line 734, in reraise
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "site-packages/docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 205, in _retrieve_server_version
  File "site-packages/docker/api/daemon.py", line 181, in version
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 228, in _get
  File "site-packages/requests/sessions.py", line 543, in get
  File "site-packages/requests/sessions.py", line 530, in request
  File "site-packages/requests/sessions.py", line 643, in send
  File "site-packages/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "site-packages/docker/api/client.py", line 188, in __init__
  File "site-packages/docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[7095] Failed to execute script docker-compose
Hackintosh:weather-app valtteri$ 
Hackintosh:weather-app valtteri$ docker-compose up -d
Creating network "weather-app_default" with the default driver
Creating weather-app_db_1           ... done
Creating weather-app_backend_1      ... done
Creating weather-app_backend_test_1 ... done
Creating weather-app_mywebsql_1     ... done
Hackintosh:weather-app valtteri$ docker-compose down
Stopping weather-app_backend_test_1 ... done
Stopping weather-app_backend_1      ... done
Stopping weather-app_mywebsql_1     ... done
Stopping weather-app_db_1           ... done
Removing weather-app_backend_test_1 ... done
Removing weather-app_backend_1      ... done
Removing weather-app_mywebsql_1     ... done
Removing weather-app_db_1           ... done
Removing network weather-app_default
Hackintosh:weather-app valtteri$ docker-compose up -d
Creating network "weather-app_default" with the default driver
Creating weather-app_db_1           ... done
Creating weather-app_backend_test_1 ... done
Creating weather-app_backend_1      ... done
Creating weather-app_mywebsql_1     ... done
Hackintosh:weather-app valtteri$ docker-compose logs -f
Attaching to weather-app_backend_1, weather-app_backend_test_1, weather-app_mywebsql_1, weather-app_db_1
backend_1       | 
backend_1       | > backend@1.0.0 dev
backend_1       | > nodemon src/index.js -w src --exec babel-node
backend_1       | 
backend_1       | [nodemon] 2.0.7
backend_1       | [nodemon] to restart at any time, enter `rs`
backend_1       | [nodemon] watching path(s): src/**/*
backend_1       | [nodemon] watching extensions: js,mjs,json
backend_1       | [nodemon] starting `babel-node src/index.js`
backend_1       | App listening on port 9000
backend_1       | Error occurred: Error: connect ECONNREFUSED 172.19.0.2:3306
backend_1       |     at Object.createConnection (/opt/app/node_modules/mysql2/promise.js:241:31)
backend_1       |     at _callee$ (/opt/app/src/index.js:29:30)
backend_1       |     at tryCatch (/opt/app/node_modules/regenerator-runtime/runtime.js:65:40)
backend_1       |     at Generator.invoke [as _invoke] (/opt/app/node_modules/regenerator-runtime/runtime.js:303:22)
backend_1       |     at Generator.prototype.<computed> [as next] (/opt/app/node_modules/regenerator-runtime/runtime.js:117:21)
backend_1       |     at step (/opt/app/src/index.js:21:191)
backend_1       |     at /opt/app/src/index.js:21:437
backend_1       |     at new Promise (<anonymous>)
backend_1       |     at /opt/app/src/index.js:21:99
backend_1       |     at /opt/app/src/index.js:27:1 {
backend_1       |   code: 'ECONNREFUSED',
backend_1       |   errno: -111,
backend_1       |   sqlState: undefined
backend_1       | }
backend_1       | 
backend_1       |   Error: connect ECONNREFUSED 172.19.0.2:3306
backend_1       |       at Object.createConnection (/opt/app/node_modules/mysql2/promise.js:241:31)
backend_1       |       at _callee$ (/opt/app/src/index.js:29:30)
backend_1       |       at tryCatch (/opt/app/node_modules/regenerator-runtime/runtime.js:65:40)
backend_1       |       at Generator.invoke [as _invoke] (/opt/app/node_modules/regenerator-runtime/runtime.js:303:22)
backend_1       |       at Generator.prototype.<computed> [as next] (/opt/app/node_modules/regenerator-runtime/runtime.js:117:21)
backend_1       |       at step (/opt/app/src/index.js:21:191)
backend_1       |       at /opt/app/src/index.js:21:437
backend_1       |       at new Promise (<anonymous>)
backend_1       |       at /opt/app/src/index.js:21:99
backend_1       |       at /opt/app/src/index.js:27:1
backend_1       | 
backend_test_1  | 
backend_test_1  | > backend@1.0.0 test:watch
backend_test_1  | > nodemon -w src --exec 'npm test'
backend_test_1  | 
backend_test_1  | [nodemon] 2.0.7
backend_test_1  | [nodemon] to restart at any time, enter `rs`
backend_test_1  | [nodemon] watching path(s): src/**/*
backend_test_1  | [nodemon] watching extensions: js,mjs,json
backend_test_1  | [nodemon] starting `npm test`
backend_test_1  | 
backend_test_1  | > backend@1.0.0 test
backend_test_1  | > npm run lint:prettier
backend_test_1  | 
backend_test_1  | 
backend_test_1  | > backend@1.0.0 lint:prettier
backend_test_1  | > npx prettier --check 'src/**/*'
backend_test_1  | 
backend_test_1  | npm WARN exec The following package was not found and will be installed: prettier
backend_test_1  | Checking formatting...
backend_test_1  | [warn] src/index.js
backend_test_1  | [warn] Code style issues found in the above file(s). Forgot to run Prettier?
backend_test_1  | npm ERR! code 1
backend_test_1  | npm ERR! path /opt/app
backend_test_1  | npm ERR! command failed
backend_test_1  | npm ERR! command sh -c prettier "--check" "src/**/*"
backend_test_1  | 
backend_test_1  | npm ERR! A complete log of this run can be found in:
backend_test_1  | npm ERR!     /root/.npm/_logs/2021-02-08T21_48_58_263Z-debug.log
backend_test_1  | npm ERR! code 1
backend_test_1  | npm ERR! path /opt/app
backend_test_1  | npm ERR! command failed
backend_test_1  | npm ERR! command sh -c npx prettier --check 'src/**/*'
backend_test_1  | 
backend_test_1  | npm ERR! A complete log of this run can be found in:
backend_test_1  | npm ERR!     /root/.npm/_logs/2021-02-08T21_48_58_294Z-debug.log
backend_test_1  | npm ERR! code 1
backend_test_1  | npm ERR! path /opt/app
backend_test_1  | npm ERR! command failed
backend_test_1  | npm ERR! command sh -c npm run lint:prettier
backend_test_1  | 
backend_test_1  | npm ERR! A complete log of this run can be found in:
backend_test_1  | npm ERR!     /root/.npm/_logs/2021-02-08T21_48_58_323Z-debug.log
backend_test_1  | [nodemon] app crashed - waiting for file changes before starting...
mywebsql_1      | Starting pre-service scritps in /etc/my_init.d
mywebsql_1      | *** Running: /etc/my_init.d/startup.sh
mywebsql_1      | starting rc.local scritps
mywebsql_1      | Booting runit daemon...
mywebsql_1      | Process runsvdir running with PID 129
db_1            | Initializing database
db_1            | 2021-02-08T21:48:47.070428Z 0 [Note] Basedir set to /usr/
db_1            | 2021-02-08T21:48:47.070566Z 0 [Warning] The syntax '--symbolic-links/-s' is deprecated and will be removed in a future release
db_1            | 2021-02-08T21:48:47.071423Z 0 [Warning] You need to use --log-bin to make --log-slave-updates work.
db_1            | libnuma: Warning: /sys not mounted or invalid. Assuming one node: No such file or directory
db_1            | mbind: Operation not permitted
db_1            | mbind: Operation not permitted
db_1            | 2021-02-08T21:48:49.534070Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 6d6ab38a-6a57-11eb-8835-0242ac130002.
db_1            | 2021-02-08T21:48:49.535330Z 0 [Warning] You have not provided a mandatory server-id. Servers in a replication topology must have unique server-ids. Please refer to the proper server start-up parameters documentation.
db_1            | 2021-02-08T21:48:49.537168Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
db_1            | 2021-02-08T21:48:49.540052Z 5 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
db_1            | 2021-02-08T21:48:51.425458Z 5 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:51.426079Z 5 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:51.426166Z 5 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:51.426380Z 5 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:51.426447Z 5 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:51.426489Z 5 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:51.426748Z 5 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:51.426911Z 5 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | Database initialized
db_1            | Initializing certificates
db_1            | Generating a 2048 bit RSA private key
db_1            | ..............................+++
db_1            | ..+++
db_1            | unable to write 'random state'
db_1            | writing new private key to 'ca-key.pem'
db_1            | -----
db_1            | Generating a 2048 bit RSA private key
db_1            | ....................+++
db_1            | ...................................................+++
db_1            | unable to write 'random state'
db_1            | writing new private key to 'server-key.pem'
db_1            | -----
db_1            | Generating a 2048 bit RSA private key
db_1            | .........+++
db_1            | .........+++
db_1            | unable to write 'random state'
db_1            | writing new private key to 'client-key.pem'
db_1            | -----
db_1            | Certificates initialized
db_1            | MySQL init process in progress...
db_1            | 2021-02-08T21:48:55.151428Z 0 [Note] Basedir set to /usr/
db_1            | 2021-02-08T21:48:55.153771Z 0 [Warning] The syntax '--symbolic-links/-s' is deprecated and will be removed in a future release
db_1            | 2021-02-08T21:48:55.153846Z 0 [Note] --secure-file-priv is set to NULL. Operations related to importing and exporting data are disabled
db_1            | 2021-02-08T21:48:55.155071Z 0 [Note] /usr/sbin/mysqld (mysqld 8.0.3-rc-log) starting as process 87 ...
db_1            | 2021-02-08T21:48:55.163507Z 0 [Warning] No argument was provided to --log-bin, and --log-bin-index was not used; so replication may break when this MySQL server acts as a master and has his hostname changed!! Please use '--log-bin=879ebea1311f-bin' to avoid this problem.
db_1            | 2021-02-08T21:48:55.196251Z 0 [Note] InnoDB: Using Linux native AIO
db_1            | 2021-02-08T21:48:55.196356Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1            | 2021-02-08T21:48:55.198193Z 1 [Note] InnoDB: PUNCH HOLE support available
db_1            | 2021-02-08T21:48:55.198312Z 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1            | 2021-02-08T21:48:55.198503Z 1 [Note] InnoDB: Uses event mutexes
db_1            | 2021-02-08T21:48:55.198519Z 1 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1            | 2021-02-08T21:48:55.198529Z 1 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1            | 2021-02-08T21:48:55.199910Z 1 [Note] InnoDB: Number of pools: 1
db_1            | 2021-02-08T21:48:55.200367Z 1 [Note] InnoDB: Using CPU crc32 instructions
db_1            | 2021-02-08T21:48:55.205126Z 1 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1            | libnuma: Warning: /sys not mounted or invalid. Assuming one node: No such file or directory
db_1            | mbind: Operation not permitted
db_1            | mbind: Operation not permitted
db_1            | 2021-02-08T21:48:55.230350Z 1 [Note] InnoDB: Completed initialization of buffer pool
db_1            | 2021-02-08T21:48:55.232253Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1            | 2021-02-08T21:48:55.247831Z 1 [Note] InnoDB: Using 'tablespaces.open.2' max LSN: 13791917
db_1            | 2021-02-08T21:48:55.251368Z 1 [Note] InnoDB: Applying a batch of 0 redo log records ...
db_1            | 2021-02-08T21:48:55.251400Z 1 [Note] InnoDB: Apply batch completed!
db_1            | 2021-02-08T21:48:55.256103Z 1 [Note] InnoDB: Opened 2 existing undo tablespaces.
db_1            | 2021-02-08T21:48:55.270455Z 1 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1            | 2021-02-08T21:48:55.270565Z 1 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1            | 2021-02-08T21:48:55.377844Z 1 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1            | 2021-02-08T21:48:55.386612Z 1 [Note] InnoDB: Created 128 and tracked 128 new rollback segment(s) in the temporary tablespace. 128 are now active.
db_1            | 2021-02-08T21:48:55.389061Z 1 [Note] InnoDB: 8.0.3 started; log sequence number 15051088
db_1            | 2021-02-08T21:48:55.575486Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1            | 2021-02-08T21:48:55.588999Z 0 [Note] InnoDB: Buffer pool(s) load completed at 210208 21:48:55
db_1            | 2021-02-08T21:48:55.602898Z 1 [Note] Found data dictionary with version 1
db_1            | 2021-02-08T21:48:55.718345Z 0 [Note] InnoDB: DDL log recovery : begin
db_1            | 2021-02-08T21:48:55.718890Z 0 [Note] InnoDB: DDL log recovery : end
db_1            | 2021-02-08T21:48:55.722394Z 0 [Note] InnoDB: Waiting for purge to start
db_1            | 2021-02-08T21:48:55.777628Z 0 [Warning] You have not provided a mandatory server-id. Servers in a replication topology must have unique server-ids. Please refer to the proper server start-up parameters documentation.
db_1            | 2021-02-08T21:48:55.781013Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1            | 2021-02-08T21:48:55.781585Z 0 [Warning] CA certificate ca.pem is self signed.
db_1            | 2021-02-08T21:48:55.801690Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:55.801735Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:55.801746Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:55.801765Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:55.801772Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:55.802007Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:55.807185Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:55.807492Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:55.816044Z 0 [Note] /usr/sbin/mysqld: ready for connections. Version: '8.0.3-rc-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
db_1            | 2021-02-08T21:48:55.816281Z 4 [Note] Event Scheduler: scheduler thread started with id 4
db_1            | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
db_1            | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
db_1            | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
db_1            | 2021-02-08T21:48:59.823308Z 9 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:59.823362Z 9 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:59.823373Z 9 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:59.823389Z 9 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:59.823607Z 9 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:59.823646Z 9 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:59.823914Z 9 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:48:59.823945Z 9 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | mysql: [Warning] Using a password on the command line interface can be insecure.
db_1            | 
db_1            | 2021-02-08T21:48:59.852794Z 0 [Note] Giving 1 client threads a chance to die gracefully
db_1            | 2021-02-08T21:48:59.852894Z 0 [Note] Shutting down slave threads
db_1            | 2021-02-08T21:48:59.852903Z 0 [Note] Event Scheduler: Killing the scheduler thread, thread id 4
db_1            | 2021-02-08T21:48:59.852908Z 0 [Note] Event Scheduler: Waiting for the scheduler thread to reply
db_1            | 2021-02-08T21:48:59.853103Z 0 [Note] Event Scheduler: Stopped
db_1            | 2021-02-08T21:48:59.853133Z 0 [Note] Forcefully disconnecting 0 remaining clients
db_1            | 2021-02-08T21:48:59.853139Z 0 [Note] Event Scheduler: Purging the queue. 0 events
db_1            | 2021-02-08T21:48:59.853490Z 0 [Note] InnoDB: FTS optimize thread exiting.
db_1            | 2021-02-08T21:48:59.957022Z 0 [Note] Binlog end
db_1            | 2021-02-08T21:48:59.960498Z 0 [Note] Shutting down plugin 'ngram'
db_1            | 2021-02-08T21:48:59.960755Z 0 [Note] Shutting down plugin 'BLACKHOLE'
db_1            | 2021-02-08T21:48:59.960802Z 0 [Note] Shutting down plugin 'ARCHIVE'
db_1            | 2021-02-08T21:48:59.960823Z 0 [Note] Shutting down plugin 'INNODB_CACHED_INDEXES'
db_1            | 2021-02-08T21:48:59.960833Z 0 [Note] Shutting down plugin 'INNODB_VIRTUAL'
db_1            | 2021-02-08T21:48:59.960851Z 0 [Note] Shutting down plugin 'INNODB_COLUMNS'
db_1            | 2021-02-08T21:48:59.960860Z 0 [Note] Shutting down plugin 'INNODB_TABLESPACES'
db_1            | 2021-02-08T21:48:59.960872Z 0 [Note] Shutting down plugin 'INNODB_INDEXES'
db_1            | 2021-02-08T21:48:59.961054Z 0 [Note] Shutting down plugin 'INNODB_TABLESTATS'
db_1            | 2021-02-08T21:48:59.961131Z 0 [Note] Shutting down plugin 'INNODB_TABLES'
db_1            | 2021-02-08T21:48:59.961214Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
db_1            | 2021-02-08T21:48:59.961280Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
db_1            | 2021-02-08T21:48:59.961290Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
db_1            | 2021-02-08T21:48:59.961299Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
db_1            | 2021-02-08T21:48:59.961307Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
db_1            | 2021-02-08T21:48:59.961315Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
db_1            | 2021-02-08T21:48:59.961323Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
db_1            | 2021-02-08T21:48:59.961332Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
db_1            | 2021-02-08T21:48:59.961340Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
db_1            | 2021-02-08T21:48:59.961348Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
db_1            | 2021-02-08T21:48:59.961356Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
db_1            | 2021-02-08T21:48:59.961364Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
db_1            | 2021-02-08T21:48:59.961372Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
db_1            | 2021-02-08T21:48:59.961382Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
db_1            | 2021-02-08T21:48:59.961390Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
db_1            | 2021-02-08T21:48:59.961398Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
db_1            | 2021-02-08T21:48:59.961501Z 0 [Note] Shutting down plugin 'INNODB_CMP'
db_1            | 2021-02-08T21:48:59.961548Z 0 [Note] Shutting down plugin 'INNODB_TRX'
db_1            | 2021-02-08T21:48:59.961558Z 0 [Note] Shutting down plugin 'InnoDB'
db_1            | 2021-02-08T21:48:59.961630Z 0 [Note] InnoDB: Starting shutdown...
db_1            | 2021-02-08T21:49:00.063657Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
db_1            | 2021-02-08T21:49:00.064111Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 210208 21:49:00
db_1            | 2021-02-08T21:49:01.495329Z 0 [Note] InnoDB: Shutdown completed; log sequence number 26009526
db_1            | 2021-02-08T21:49:01.497756Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
db_1            | 2021-02-08T21:49:01.497814Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
db_1            | 2021-02-08T21:49:01.497823Z 0 [Note] Shutting down plugin 'MyISAM'
db_1            | 2021-02-08T21:49:01.497881Z 0 [Note] Shutting down plugin 'CSV'
db_1            | 2021-02-08T21:49:01.497896Z 0 [Note] Shutting down plugin 'MEMORY'
db_1            | 2021-02-08T21:49:01.497899Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
db_1            | 2021-02-08T21:49:01.497993Z 0 [Note] Shutting down plugin 'TempTable'
db_1            | 2021-02-08T21:49:01.497998Z 0 [Note] Shutting down plugin 'sha2_cache_cleaner'
db_1            | 2021-02-08T21:49:01.498001Z 0 [Note] Shutting down plugin 'caching_sha2_password'
db_1            | 2021-02-08T21:49:01.498007Z 0 [Note] Shutting down plugin 'sha256_password'
db_1            | 2021-02-08T21:49:01.498009Z 0 [Note] Shutting down plugin 'mysql_native_password'
db_1            | 2021-02-08T21:49:01.498247Z 0 [Note] Shutting down plugin 'binlog'
db_1            | 2021-02-08T21:49:01.500967Z 0 [Note] /usr/sbin/mysqld: Shutdown complete
db_1            | 
db_1            | 
db_1            | MySQL init process done. Ready for start up.
db_1            | 
db_1            | 2021-02-08T21:49:01.736034Z 0 [Note] Basedir set to /usr/
db_1            | 2021-02-08T21:49:01.736167Z 0 [Warning] The syntax '--symbolic-links/-s' is deprecated and will be removed in a future release
db_1            | 2021-02-08T21:49:01.736209Z 0 [Note] --secure-file-priv is set to NULL. Operations related to importing and exporting data are disabled
db_1            | 2021-02-08T21:49:01.736230Z 0 [Note] /usr/sbin/mysqld (mysqld 8.0.3-rc-log) starting as process 1 ...
db_1            | 2021-02-08T21:49:01.738044Z 0 [Warning] No argument was provided to --log-bin, and --log-bin-index was not used; so replication may break when this MySQL server acts as a master and has his hostname changed!! Please use '--log-bin=879ebea1311f-bin' to avoid this problem.
db_1            | 2021-02-08T21:49:01.739259Z 0 [Note] InnoDB: Using Linux native AIO
db_1            | 2021-02-08T21:49:01.739342Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1            | 2021-02-08T21:49:01.740736Z 1 [Note] InnoDB: PUNCH HOLE support available
db_1            | 2021-02-08T21:49:01.740824Z 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1            | 2021-02-08T21:49:01.740869Z 1 [Note] InnoDB: Uses event mutexes
db_1            | 2021-02-08T21:49:01.740897Z 1 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1            | 2021-02-08T21:49:01.740943Z 1 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1            | 2021-02-08T21:49:01.741192Z 1 [Note] InnoDB: Number of pools: 1
db_1            | 2021-02-08T21:49:01.741351Z 1 [Note] InnoDB: Using CPU crc32 instructions
db_1            | 2021-02-08T21:49:01.742274Z 1 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1            | libnuma: Warning: /sys not mounted or invalid. Assuming one node: No such file or directory
db_1            | mbind: Operation not permitted
db_1            | mbind: Operation not permitted
db_1            | 2021-02-08T21:49:01.749150Z 1 [Note] InnoDB: Completed initialization of buffer pool
db_1            | 2021-02-08T21:49:01.750334Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1            | 2021-02-08T21:49:01.761662Z 1 [Note] InnoDB: Using 'tablespaces.open.1' max LSN: 15051133
db_1            | 2021-02-08T21:49:01.763924Z 1 [Note] InnoDB: Applying a batch of 0 redo log records ...
db_1            | 2021-02-08T21:49:01.764035Z 1 [Note] InnoDB: Apply batch completed!
db_1            | 2021-02-08T21:49:01.764687Z 1 [Note] InnoDB: Opened 2 existing undo tablespaces.
db_1            | 2021-02-08T21:49:01.771637Z 1 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1            | 2021-02-08T21:49:01.771816Z 1 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1            | 2021-02-08T21:49:01.813782Z 1 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1            | 2021-02-08T21:49:01.815995Z 1 [Note] InnoDB: Created 128 and tracked 128 new rollback segment(s) in the temporary tablespace. 128 are now active.
db_1            | 2021-02-08T21:49:01.816287Z 1 [Note] InnoDB: 8.0.3 started; log sequence number 26009526
db_1            | 2021-02-08T21:49:01.851966Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1            | 2021-02-08T21:49:01.861048Z 1 [Note] Found data dictionary with version 1
db_1            | 2021-02-08T21:49:01.873665Z 0 [Note] InnoDB: DDL log recovery : begin
db_1            | 2021-02-08T21:49:01.873723Z 0 [Note] InnoDB: DDL log recovery : end
db_1            | 2021-02-08T21:49:01.874037Z 0 [Note] InnoDB: Waiting for purge to start
db_1            | 2021-02-08T21:49:01.930494Z 0 [Warning] You have not provided a mandatory server-id. Servers in a replication topology must have unique server-ids. Please refer to the proper server start-up parameters documentation.
db_1            | 2021-02-08T21:49:01.942215Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1            | 2021-02-08T21:49:01.942568Z 0 [Warning] CA certificate ca.pem is self signed.
db_1            | 2021-02-08T21:49:01.944206Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db_1            | 2021-02-08T21:49:01.944409Z 0 [Note] IPv6 is available.
db_1            | 2021-02-08T21:49:01.944444Z 0 [Note]   - '::' resolves to '::';
db_1            | 2021-02-08T21:49:01.944498Z 0 [Note] Server socket created on IP: '::'.
db_1            | 2021-02-08T21:49:01.952308Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:49:01.952350Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:49:01.952359Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:49:01.952376Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:49:01.952393Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:49:01.952403Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:49:01.955164Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:49:01.955196Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T21:49:01.959144Z 4 [Note] Event Scheduler: scheduler thread started with id 4
db_1            | 2021-02-08T21:49:01.959180Z 0 [Note] /usr/sbin/mysqld: ready for connections. Version: '8.0.3-rc-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
db_1            | 2021-02-08T21:49:02.855938Z 0 [Note] InnoDB: Buffer pool(s) load completed at 210208 21:49:02
backend_1       | Error occurred: Error: Table 'db_1.test_table' doesn't exist
backend_1       |     at PromiseConnection.execute (/opt/app/node_modules/mysql2/promise.js:110:22)
backend_1       |     at _callee$ (/opt/app/src/index.js:30:31)
backend_1       |     at tryCatch (/opt/app/node_modules/regenerator-runtime/runtime.js:65:40)
backend_1       |     at Generator.invoke [as _invoke] (/opt/app/node_modules/regenerator-runtime/runtime.js:303:22)
backend_1       |     at Generator.prototype.<computed> [as next] (/opt/app/node_modules/regenerator-runtime/runtime.js:117:21)
backend_1       |     at step (/opt/app/src/index.js:21:191)
backend_1       |     at /opt/app/src/index.js:21:361
backend_1       |     at processTicksAndRejections (node:internal/process/task_queues:94:5) {
backend_1       |   code: 'ER_NO_SUCH_TABLE',
backend_1       |   errno: 1146,
backend_1       |   sqlState: '42S02',
backend_1       |   sqlMessage: "Table 'db_1.test_table' doesn't exist"
backend_1       | }
backend_1       | 
backend_1       |   Error: Table 'db_1.test_table' doesn't exist
backend_1       |       at PromiseConnection.execute (/opt/app/node_modules/mysql2/promise.js:110:22)
backend_1       |       at _callee$ (/opt/app/src/index.js:30:31)
backend_1       |       at tryCatch (/opt/app/node_modules/regenerator-runtime/runtime.js:65:40)
backend_1       |       at Generator.invoke [as _invoke] (/opt/app/node_modules/regenerator-runtime/runtime.js:303:22)
backend_1       |       at Generator.prototype.<computed> [as next] (/opt/app/node_modules/regenerator-runtime/runtime.js:117:21)
backend_1       |       at step (/opt/app/src/index.js:21:191)
backend_1       |       at /opt/app/src/index.js:21:361
backend_1       |       at processTicksAndRejections (node:internal/process/task_queues:94:5)
backend_1       | 
db_1            | mbind: Operation not permitted
backend_1       | Data fetched: [ BinaryRow { id: 123123, field_1: 'moikka', field_2: 12412435 } ]
db_1            | mbind: Operation not permitted
^CERROR: Aborting.
Hackintosh:weather-app valtteri$ 
Hackintosh:weather-app valtteri$ docker-compose down
Stopping weather-app_backend_1      ... done
Stopping weather-app_backend_test_1 ... done
Stopping weather-app_mywebsql_1     ... done
Stopping weather-app_db_1           ... done
Removing weather-app_backend_1      ... done
Removing weather-app_backend_test_1 ... done
Removing weather-app_mywebsql_1     ... done
Removing weather-app_db_1           ... done
Removing network weather-app_default
Hackintosh:weather-app valtteri$ docker-compose up -d
Creating network "weather-app_default" with the default driver
Creating weather-app_backend_test_1 ... done
Creating weather-app_db_1           ... done
Creating weather-app_backend_1      ... done
Creating weather-app_mywebsql_1     ... done
Hackintosh:weather-app valtteri$ docker-compose logs -f
Attaching to weather-app_backend_test_1, weather-app_backend_1, weather-app_mywebsql_1, weather-app_db_1
backend_test_1  | 
backend_test_1  | > backend@1.0.0 test:watch
backend_test_1  | > nodemon -w src --exec 'npm test'
backend_test_1  | 
backend_test_1  | [nodemon] 2.0.7
backend_test_1  | [nodemon] to restart at any time, enter `rs`
backend_test_1  | [nodemon] watching path(s): src/**/*
backend_test_1  | [nodemon] watching extensions: js,mjs,json
backend_test_1  | [nodemon] starting `npm test`
backend_test_1  | 
backend_test_1  | > backend@1.0.0 test
backend_test_1  | > npm run lint:prettier
backend_test_1  | 
backend_test_1  | 
backend_test_1  | > backend@1.0.0 lint:prettier
backend_test_1  | > npx prettier --check 'src/**/*'
backend_test_1  | 
backend_test_1  | npm WARN exec The following package was not found and will be installed: prettier
backend_test_1  | Checking formatting...
backend_test_1  | [warn] src/index.js
backend_test_1  | [warn] Code style issues found in the above file(s). Forgot to run Prettier?
backend_test_1  | npm ERR! code 1
backend_test_1  | npm ERR! path /opt/app
backend_test_1  | npm ERR! command failed
backend_test_1  | npm ERR! command sh -c prettier "--check" "src/**/*"
backend_test_1  | 
backend_test_1  | npm ERR! A complete log of this run can be found in:
backend_test_1  | npm ERR!     /root/.npm/_logs/2021-02-08T22_08_27_952Z-debug.log
backend_test_1  | npm ERR! code 1
backend_test_1  | npm ERR! path /opt/app
backend_test_1  | npm ERR! command failed
backend_test_1  | npm ERR! command sh -c npx prettier --check 'src/**/*'
backend_test_1  | 
backend_test_1  | npm ERR! A complete log of this run can be found in:
backend_test_1  | npm ERR!     /root/.npm/_logs/2021-02-08T22_08_28_023Z-debug.log
backend_test_1  | npm ERR! code 1
backend_test_1  | npm ERR! path /opt/app
backend_test_1  | npm ERR! command failed
backend_test_1  | npm ERR! command sh -c npm run lint:prettier
backend_test_1  | 
backend_test_1  | npm ERR! A complete log of this run can be found in:
backend_test_1  | npm ERR!     /root/.npm/_logs/2021-02-08T22_08_28_128Z-debug.log
backend_test_1  | [nodemon] app crashed - waiting for file changes before starting...
mywebsql_1      | Starting pre-service scritps in /etc/my_init.d
mywebsql_1      | *** Running: /etc/my_init.d/startup.sh
mywebsql_1      | starting rc.local scritps
mywebsql_1      | Booting runit daemon...
mywebsql_1      | Process runsvdir running with PID 129
backend_1       | 
backend_1       | > backend@1.0.0 dev
backend_1       | > nodemon src/index.js -w src --exec babel-node
backend_1       | 
backend_1       | [nodemon] 2.0.7
backend_1       | [nodemon] to restart at any time, enter `rs`
backend_1       | [nodemon] watching path(s): src/**/*
backend_1       | [nodemon] watching extensions: js,mjs,json
backend_1       | [nodemon] starting `babel-node src/index.js`
backend_1       | App listening on port 9000
backend_1       | Error occurred: Error: connect ECONNREFUSED 172.20.0.3:3306
backend_1       |     at Object.createConnection (/opt/app/node_modules/mysql2/promise.js:241:31)
backend_1       |     at _callee$ (/opt/app/src/index.js:29:30)
backend_1       |     at tryCatch (/opt/app/node_modules/regenerator-runtime/runtime.js:65:40)
backend_1       |     at Generator.invoke [as _invoke] (/opt/app/node_modules/regenerator-runtime/runtime.js:303:22)
backend_1       |     at Generator.prototype.<computed> [as next] (/opt/app/node_modules/regenerator-runtime/runtime.js:117:21)
backend_1       |     at step (/opt/app/src/index.js:21:191)
backend_1       |     at /opt/app/src/index.js:21:437
backend_1       |     at new Promise (<anonymous>)
backend_1       |     at /opt/app/src/index.js:21:99
backend_1       |     at /opt/app/src/index.js:27:1 {
backend_1       |   code: 'ECONNREFUSED',
backend_1       |   errno: -111,
backend_1       |   sqlState: undefined
backend_1       | }
backend_1       | 
backend_1       |   Error: connect ECONNREFUSED 172.20.0.3:3306
backend_1       |       at Object.createConnection (/opt/app/node_modules/mysql2/promise.js:241:31)
backend_1       |       at _callee$ (/opt/app/src/index.js:29:30)
backend_1       |       at tryCatch (/opt/app/node_modules/regenerator-runtime/runtime.js:65:40)
backend_1       |       at Generator.invoke [as _invoke] (/opt/app/node_modules/regenerator-runtime/runtime.js:303:22)
backend_1       |       at Generator.prototype.<computed> [as next] (/opt/app/node_modules/regenerator-runtime/runtime.js:117:21)
backend_1       |       at step (/opt/app/src/index.js:21:191)
backend_1       |       at /opt/app/src/index.js:21:437
backend_1       |       at new Promise (<anonymous>)
backend_1       |       at /opt/app/src/index.js:21:99
backend_1       |       at /opt/app/src/index.js:27:1
backend_1       | 
backend_1       | Error occurred: Error: Table 'tietokanta.test_table' doesn't exist
backend_1       |     at PromiseConnection.execute (/opt/app/node_modules/mysql2/promise.js:110:22)
backend_1       |     at _callee$ (/opt/app/src/index.js:30:31)
backend_1       |     at tryCatch (/opt/app/node_modules/regenerator-runtime/runtime.js:65:40)
backend_1       |     at Generator.invoke [as _invoke] (/opt/app/node_modules/regenerator-runtime/runtime.js:303:22)
backend_1       |     at Generator.prototype.<computed> [as next] (/opt/app/node_modules/regenerator-runtime/runtime.js:117:21)
backend_1       |     at step (/opt/app/src/index.js:21:191)
backend_1       |     at /opt/app/src/index.js:21:361
backend_1       |     at processTicksAndRejections (node:internal/process/task_queues:94:5) {
backend_1       |   code: 'ER_NO_SUCH_TABLE',
backend_1       |   errno: 1146,
backend_1       |   sqlState: '42S02',
backend_1       |   sqlMessage: "Table 'tietokanta.test_table' doesn't exist"
backend_1       | }
backend_1       | 
backend_1       |   Error: Table 'tietokanta.test_table' doesn't exist
backend_1       |       at PromiseConnection.execute (/opt/app/node_modules/mysql2/promise.js:110:22)
backend_1       |       at _callee$ (/opt/app/src/index.js:30:31)
backend_1       |       at tryCatch (/opt/app/node_modules/regenerator-runtime/runtime.js:65:40)
backend_1       |       at Generator.invoke [as _invoke] (/opt/app/node_modules/regenerator-runtime/runtime.js:303:22)
backend_1       |       at Generator.prototype.<computed> [as next] (/opt/app/node_modules/regenerator-runtime/runtime.js:117:21)
backend_1       |       at step (/opt/app/src/index.js:21:191)
backend_1       |       at /opt/app/src/index.js:21:361
backend_1       |       at processTicksAndRejections (node:internal/process/task_queues:94:5)
backend_1       | 
db_1            | Initializing database
db_1            | 2021-02-08T22:08:17.568830Z 0 [Note] Basedir set to /usr/
db_1            | 2021-02-08T22:08:17.568978Z 0 [Warning] The syntax '--symbolic-links/-s' is deprecated and will be removed in a future release
db_1            | 2021-02-08T22:08:17.570037Z 0 [Warning] You need to use --log-bin to make --log-slave-updates work.
db_1            | libnuma: Warning: /sys not mounted or invalid. Assuming one node: No such file or directory
db_1            | mbind: Operation not permitted
db_1            | mbind: Operation not permitted
db_1            | 2021-02-08T22:08:19.506849Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 26c6610c-6a5a-11eb-86aa-0242ac140003.
db_1            | 2021-02-08T22:08:19.508252Z 0 [Warning] You have not provided a mandatory server-id. Servers in a replication topology must have unique server-ids. Please refer to the proper server start-up parameters documentation.
db_1            | 2021-02-08T22:08:19.512759Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
db_1            | 2021-02-08T22:08:19.515008Z 5 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
db_1            | 2021-02-08T22:08:21.268845Z 5 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:21.268906Z 5 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:21.268919Z 5 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:21.268942Z 5 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:21.268995Z 5 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:21.269012Z 5 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:21.269121Z 5 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:21.269131Z 5 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | Database initialized
db_1            | Initializing certificates
db_1            | Generating a 2048 bit RSA private key
db_1            | .................+++
db_1            | ...................................................+++
db_1            | unable to write 'random state'
db_1            | writing new private key to 'ca-key.pem'
db_1            | -----
db_1            | Generating a 2048 bit RSA private key
db_1            | ..........................+++
db_1            | ..........................................+++
db_1            | unable to write 'random state'
db_1            | writing new private key to 'server-key.pem'
db_1            | -----
db_1            | Generating a 2048 bit RSA private key
db_1            | .........+++
db_1            | .........................................................+++
db_1            | unable to write 'random state'
db_1            | writing new private key to 'client-key.pem'
db_1            | -----
db_1            | Certificates initialized
db_1            | MySQL init process in progress...
db_1            | 2021-02-08T22:08:26.317809Z 0 [Note] Basedir set to /usr/
db_1            | 2021-02-08T22:08:26.319325Z 0 [Warning] The syntax '--symbolic-links/-s' is deprecated and will be removed in a future release
db_1            | 2021-02-08T22:08:26.319489Z 0 [Note] --secure-file-priv is set to NULL. Operations related to importing and exporting data are disabled
db_1            | 2021-02-08T22:08:26.319524Z 0 [Note] /usr/sbin/mysqld (mysqld 8.0.3-rc-log) starting as process 88 ...
db_1            | 2021-02-08T22:08:26.325415Z 0 [Warning] No argument was provided to --log-bin, and --log-bin-index was not used; so replication may break when this MySQL server acts as a master and has his hostname changed!! Please use '--log-bin=f881bdec61d7-bin' to avoid this problem.
db_1            | 2021-02-08T22:08:26.385484Z 0 [Note] InnoDB: Using Linux native AIO
db_1            | 2021-02-08T22:08:26.386005Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1            | 2021-02-08T22:08:26.388886Z 1 [Note] InnoDB: PUNCH HOLE support available
db_1            | 2021-02-08T22:08:26.389097Z 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1            | 2021-02-08T22:08:26.389129Z 1 [Note] InnoDB: Uses event mutexes
db_1            | 2021-02-08T22:08:26.389140Z 1 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1            | 2021-02-08T22:08:26.389319Z 1 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1            | 2021-02-08T22:08:26.390127Z 1 [Note] InnoDB: Number of pools: 1
db_1            | 2021-02-08T22:08:26.390770Z 1 [Note] InnoDB: Using CPU crc32 instructions
db_1            | 2021-02-08T22:08:26.395990Z 1 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1            | libnuma: Warning: /sys not mounted or invalid. Assuming one node: No such file or directory
db_1            | mbind: Operation not permitted
db_1            | mbind: Operation not permitted
db_1            | 2021-02-08T22:08:26.414040Z 1 [Note] InnoDB: Completed initialization of buffer pool
db_1            | 2021-02-08T22:08:26.416689Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1            | 2021-02-08T22:08:26.434888Z 1 [Note] InnoDB: Using 'tablespaces.open.2' max LSN: 13791914
db_1            | 2021-02-08T22:08:26.438699Z 1 [Note] InnoDB: Applying a batch of 0 redo log records ...
db_1            | 2021-02-08T22:08:26.439472Z 1 [Note] InnoDB: Apply batch completed!
db_1            | 2021-02-08T22:08:26.443060Z 1 [Note] InnoDB: Opened 2 existing undo tablespaces.
db_1            | 2021-02-08T22:08:26.477622Z 1 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1            | 2021-02-08T22:08:26.477705Z 1 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1            | 2021-02-08T22:08:26.618898Z 1 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1            | 2021-02-08T22:08:26.622923Z 1 [Note] InnoDB: Created 128 and tracked 128 new rollback segment(s) in the temporary tablespace. 128 are now active.
db_1            | 2021-02-08T22:08:26.625518Z 1 [Note] InnoDB: 8.0.3 started; log sequence number 15051085
db_1            | MySQL init process in progress...
db_1            | 2021-02-08T22:08:26.921518Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1            | 2021-02-08T22:08:26.943673Z 0 [Note] InnoDB: Buffer pool(s) load completed at 210208 22:08:26
db_1            | 2021-02-08T22:08:26.980772Z 1 [Note] Found data dictionary with version 1
db_1            | 2021-02-08T22:08:27.075858Z 0 [Note] InnoDB: DDL log recovery : begin
db_1            | 2021-02-08T22:08:27.076244Z 0 [Note] InnoDB: DDL log recovery : end
db_1            | 2021-02-08T22:08:27.076512Z 0 [Note] InnoDB: Waiting for purge to start
db_1            | 2021-02-08T22:08:27.131949Z 0 [Warning] You have not provided a mandatory server-id. Servers in a replication topology must have unique server-ids. Please refer to the proper server start-up parameters documentation.
db_1            | 2021-02-08T22:08:27.134486Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1            | 2021-02-08T22:08:27.134944Z 0 [Warning] CA certificate ca.pem is self signed.
db_1            | 2021-02-08T22:08:27.166966Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:27.170629Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:27.170722Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:27.170832Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:27.170910Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:27.170980Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:27.174283Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:27.174513Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:27.183259Z 0 [Note] /usr/sbin/mysqld: ready for connections. Version: '8.0.3-rc-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
db_1            | 2021-02-08T22:08:27.183501Z 4 [Note] Event Scheduler: scheduler thread started with id 4
db_1            | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
db_1            | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
db_1            | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
db_1            | 2021-02-08T22:08:30.558979Z 9 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:30.559198Z 9 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:30.559263Z 9 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:30.559294Z 9 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:30.559349Z 9 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:30.559458Z 9 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:30.559672Z 9 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:30.559763Z 9 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | mysql: [Warning] Using a password on the command line interface can be insecure.
db_1            | 
db_1            | 2021-02-08T22:08:30.568977Z 0 [Note] Giving 1 client threads a chance to die gracefully
db_1            | 2021-02-08T22:08:30.569032Z 0 [Note] Shutting down slave threads
db_1            | 2021-02-08T22:08:30.569040Z 0 [Note] Event Scheduler: Killing the scheduler thread, thread id 4
db_1            | 2021-02-08T22:08:30.569045Z 0 [Note] Event Scheduler: Waiting for the scheduler thread to reply
db_1            | 2021-02-08T22:08:30.569252Z 0 [Note] Event Scheduler: Stopped
db_1            | 2021-02-08T22:08:30.569282Z 0 [Note] Forcefully disconnecting 0 remaining clients
db_1            | 2021-02-08T22:08:30.569288Z 0 [Note] Event Scheduler: Purging the queue. 0 events
db_1            | 2021-02-08T22:08:30.569529Z 0 [Note] InnoDB: FTS optimize thread exiting.
db_1            | 2021-02-08T22:08:30.671535Z 0 [Note] Binlog end
db_1            | 2021-02-08T22:08:30.673795Z 0 [Note] Shutting down plugin 'ngram'
db_1            | 2021-02-08T22:08:30.673879Z 0 [Note] Shutting down plugin 'BLACKHOLE'
db_1            | 2021-02-08T22:08:30.673895Z 0 [Note] Shutting down plugin 'ARCHIVE'
db_1            | 2021-02-08T22:08:30.673914Z 0 [Note] Shutting down plugin 'INNODB_CACHED_INDEXES'
db_1            | 2021-02-08T22:08:30.673924Z 0 [Note] Shutting down plugin 'INNODB_VIRTUAL'
db_1            | 2021-02-08T22:08:30.673931Z 0 [Note] Shutting down plugin 'INNODB_COLUMNS'
db_1            | 2021-02-08T22:08:30.673996Z 0 [Note] Shutting down plugin 'INNODB_TABLESPACES'
db_1            | 2021-02-08T22:08:30.674084Z 0 [Note] Shutting down plugin 'INNODB_INDEXES'
db_1            | 2021-02-08T22:08:30.674145Z 0 [Note] Shutting down plugin 'INNODB_TABLESTATS'
db_1            | 2021-02-08T22:08:30.674209Z 0 [Note] Shutting down plugin 'INNODB_TABLES'
db_1            | 2021-02-08T22:08:30.674247Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
db_1            | 2021-02-08T22:08:30.674256Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
db_1            | 2021-02-08T22:08:30.674345Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
db_1            | 2021-02-08T22:08:30.674377Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
db_1            | 2021-02-08T22:08:30.674388Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
db_1            | 2021-02-08T22:08:30.674405Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
db_1            | 2021-02-08T22:08:30.674413Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
db_1            | 2021-02-08T22:08:30.674420Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
db_1            | 2021-02-08T22:08:30.674446Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
db_1            | 2021-02-08T22:08:30.674454Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
db_1            | 2021-02-08T22:08:30.674462Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
db_1            | 2021-02-08T22:08:30.674481Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
db_1            | 2021-02-08T22:08:30.674514Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
db_1            | 2021-02-08T22:08:30.674548Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
db_1            | 2021-02-08T22:08:30.674594Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
db_1            | 2021-02-08T22:08:30.674602Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
db_1            | 2021-02-08T22:08:30.674611Z 0 [Note] Shutting down plugin 'INNODB_CMP'
db_1            | 2021-02-08T22:08:30.674680Z 0 [Note] Shutting down plugin 'INNODB_TRX'
db_1            | 2021-02-08T22:08:30.674718Z 0 [Note] Shutting down plugin 'InnoDB'
db_1            | 2021-02-08T22:08:30.674755Z 0 [Note] InnoDB: Starting shutdown...
db_1            | 2021-02-08T22:08:30.777061Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
db_1            | 2021-02-08T22:08:30.777641Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 210208 22:08:30
db_1            | 2021-02-08T22:08:32.223197Z 0 [Note] InnoDB: Shutdown completed; log sequence number 26009443
db_1            | 2021-02-08T22:08:32.225499Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
db_1            | 2021-02-08T22:08:32.225672Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
db_1            | 2021-02-08T22:08:32.225717Z 0 [Note] Shutting down plugin 'MyISAM'
db_1            | 2021-02-08T22:08:32.225794Z 0 [Note] Shutting down plugin 'CSV'
db_1            | 2021-02-08T22:08:32.225843Z 0 [Note] Shutting down plugin 'MEMORY'
db_1            | 2021-02-08T22:08:32.225855Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
db_1            | 2021-02-08T22:08:32.225950Z 0 [Note] Shutting down plugin 'TempTable'
db_1            | 2021-02-08T22:08:32.225972Z 0 [Note] Shutting down plugin 'sha2_cache_cleaner'
db_1            | 2021-02-08T22:08:32.226010Z 0 [Note] Shutting down plugin 'caching_sha2_password'
db_1            | 2021-02-08T22:08:32.226023Z 0 [Note] Shutting down plugin 'sha256_password'
db_1            | 2021-02-08T22:08:32.226096Z 0 [Note] Shutting down plugin 'mysql_native_password'
db_1            | 2021-02-08T22:08:32.226278Z 0 [Note] Shutting down plugin 'binlog'
db_1            | 2021-02-08T22:08:32.229126Z 0 [Note] /usr/sbin/mysqld: Shutdown complete
db_1            | 
db_1            | 
db_1            | MySQL init process done. Ready for start up.
db_1            | 
db_1            | 2021-02-08T22:08:32.466853Z 0 [Note] Basedir set to /usr/
db_1            | 2021-02-08T22:08:32.466984Z 0 [Warning] The syntax '--symbolic-links/-s' is deprecated and will be removed in a future release
db_1            | 2021-02-08T22:08:32.467028Z 0 [Note] --secure-file-priv is set to NULL. Operations related to importing and exporting data are disabled
db_1            | 2021-02-08T22:08:32.467049Z 0 [Note] /usr/sbin/mysqld (mysqld 8.0.3-rc-log) starting as process 1 ...
db_1            | 2021-02-08T22:08:32.468796Z 0 [Warning] No argument was provided to --log-bin, and --log-bin-index was not used; so replication may break when this MySQL server acts as a master and has his hostname changed!! Please use '--log-bin=f881bdec61d7-bin' to avoid this problem.
db_1            | 2021-02-08T22:08:32.470058Z 0 [Note] InnoDB: Using Linux native AIO
db_1            | 2021-02-08T22:08:32.470141Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1            | 2021-02-08T22:08:32.471503Z 1 [Note] InnoDB: PUNCH HOLE support available
db_1            | 2021-02-08T22:08:32.471602Z 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1            | 2021-02-08T22:08:32.471736Z 1 [Note] InnoDB: Uses event mutexes
db_1            | 2021-02-08T22:08:32.471863Z 1 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1            | 2021-02-08T22:08:32.471904Z 1 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1            | 2021-02-08T22:08:32.472211Z 1 [Note] InnoDB: Number of pools: 1
db_1            | 2021-02-08T22:08:32.472467Z 1 [Note] InnoDB: Using CPU crc32 instructions
db_1            | 2021-02-08T22:08:32.473435Z 1 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1            | libnuma: Warning: /sys not mounted or invalid. Assuming one node: No such file or directory
db_1            | mbind: Operation not permitted
db_1            | mbind: Operation not permitted
db_1            | 2021-02-08T22:08:32.480492Z 1 [Note] InnoDB: Completed initialization of buffer pool
db_1            | 2021-02-08T22:08:32.481546Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1            | 2021-02-08T22:08:32.492995Z 1 [Note] InnoDB: Using 'tablespaces.open.1' max LSN: 15051130
db_1            | 2021-02-08T22:08:32.495274Z 1 [Note] InnoDB: Applying a batch of 0 redo log records ...
db_1            | 2021-02-08T22:08:32.495366Z 1 [Note] InnoDB: Apply batch completed!
db_1            | 2021-02-08T22:08:32.496016Z 1 [Note] InnoDB: Opened 2 existing undo tablespaces.
db_1            | 2021-02-08T22:08:32.502803Z 1 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1            | 2021-02-08T22:08:32.503065Z 1 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1            | 2021-02-08T22:08:32.544336Z 1 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1            | 2021-02-08T22:08:32.548586Z 1 [Note] InnoDB: Created 128 and tracked 128 new rollback segment(s) in the temporary tablespace. 128 are now active.
db_1            | 2021-02-08T22:08:32.548975Z 1 [Note] InnoDB: 8.0.3 started; log sequence number 26009443
db_1            | 2021-02-08T22:08:32.601448Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1            | 2021-02-08T22:08:32.612644Z 1 [Note] Found data dictionary with version 1
db_1            | 2021-02-08T22:08:32.629482Z 0 [Note] InnoDB: DDL log recovery : begin
db_1            | 2021-02-08T22:08:32.629551Z 0 [Note] InnoDB: DDL log recovery : end
db_1            | 2021-02-08T22:08:32.629707Z 0 [Note] InnoDB: Waiting for purge to start
db_1            | 2021-02-08T22:08:32.683987Z 0 [Warning] You have not provided a mandatory server-id. Servers in a replication topology must have unique server-ids. Please refer to the proper server start-up parameters documentation.
db_1            | 2021-02-08T22:08:32.697493Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1            | 2021-02-08T22:08:32.697929Z 0 [Warning] CA certificate ca.pem is self signed.
db_1            | 2021-02-08T22:08:32.699699Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db_1            | 2021-02-08T22:08:32.699802Z 0 [Note] IPv6 is available.
db_1            | 2021-02-08T22:08:32.699916Z 0 [Note]   - '::' resolves to '::';
db_1            | 2021-02-08T22:08:32.699985Z 0 [Note] Server socket created on IP: '::'.
db_1            | 2021-02-08T22:08:32.708718Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:32.708767Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:32.708777Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:32.708797Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:32.708813Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:32.708824Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:32.712018Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:32.712062Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1            | 2021-02-08T22:08:32.717173Z 4 [Note] Event Scheduler: scheduler thread started with id 4
db_1            | 2021-02-08T22:08:32.717224Z 0 [Note] /usr/sbin/mysqld: ready for connections. Version: '8.0.3-rc-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
db_1            | 2021-02-08T22:08:33.605111Z 0 [Note] InnoDB: Buffer pool(s) load completed at 210208 22:08:33
db_1            | mbind: Operation not permitted
backend_1       | Error occurred: Error: Table 'tietokanta.test_table' doesn't exist
backend_1       |     at PromiseConnection.execute (/opt/app/node_modules/mysql2/promise.js:110:22)
backend_1       |     at _callee$ (/opt/app/src/index.js:30:31)
backend_1       |     at tryCatch (/opt/app/node_modules/regenerator-runtime/runtime.js:65:40)
backend_1       |     at Generator.invoke [as _invoke] (/opt/app/node_modules/regenerator-runtime/runtime.js:303:22)
backend_1       |     at Generator.prototype.<computed> [as next] (/opt/app/node_modules/regenerator-runtime/runtime.js:117:21)
backend_1       |     at step (/opt/app/src/index.js:21:191)
backend_1       |     at /opt/app/src/index.js:21:361
backend_1       |     at processTicksAndRejections (node:internal/process/task_queues:94:5) {
backend_1       |   code: 'ER_NO_SUCH_TABLE',
backend_1       |   errno: 1146,
backend_1       |   sqlState: '42S02',
backend_1       |   sqlMessage: "Table 'tietokanta.test_table' doesn't exist"
backend_1       | }
backend_1       | 
backend_1       |   Error: Table 'tietokanta.test_table' doesn't exist
backend_1       |       at PromiseConnection.execute (/opt/app/node_modules/mysql2/promise.js:110:22)
backend_1       |       at _callee$ (/opt/app/src/index.js:30:31)
backend_1       |       at tryCatch (/opt/app/node_modules/regenerator-runtime/runtime.js:65:40)
backend_1       |       at Generator.invoke [as _invoke] (/opt/app/node_modules/regenerator-runtime/runtime.js:303:22)
backend_1       |       at Generator.prototype.<computed> [as next] (/opt/app/node_modules/regenerator-runtime/runtime.js:117:21)
backend_1       |       at step (/opt/app/src/index.js:21:191)
backend_1       |       at /opt/app/src/index.js:21:361
backend_1       |       at processTicksAndRejections (node:internal/process/task_queues:94:5)
backend_1       | 
db_1            | mbind: Operation not permitted
backend_1       | Data fetched: [ BinaryRow { id: 12, field_1: 'moikka', field_2: 23 } ]
backend_1       | Data fetched: [ BinaryRow { id: 12, field_1: 'moikka', field_2: 23 } ]
db_1            | mbind: Operation not permitted
backend_1       | Data fetched: [ BinaryRow { id: 12, field_1: 'moikka', field_2: 23 } ]
backend_1       | Data fetched: [ BinaryRow { id: 12, field_1: 'moikka', field_2: 23 } ]
backend_1       | Data fetched: [ BinaryRow { id: 12, field_1: 'moikka', field_2: 23 } ]
db_1            | mbind: Operation not permitted
backend_1       | Data fetched: [ BinaryRow { id: 12, field_1: 'moikka', field_2: 23 } ]
mywebsql_1      | Begin shutting down runit services...
db_1            | 2021-02-08T22:28:26.293069Z 24 [Note] Aborted connection 24 to db: 'tietokanta' user: 'root' host: '172.20.0.5' (Got an error reading communication packets)
db_1            | 2021-02-08T22:28:26.293510Z 50 [Note] Aborted connection 50 to db: 'tietokanta' user: 'root' host: '172.20.0.5' (Got an error reading communication packets)
db_1            | 2021-02-08T22:28:26.293754Z 51 [Note] Aborted connection 51 to db: 'tietokanta' user: 'root' host: '172.20.0.5' (Got an error reading communication packets)
db_1            | 2021-02-08T22:28:26.293766Z 25 [Note] Aborted connection 25 to db: 'tietokanta' user: 'root' host: '172.20.0.5' (Got an error reading communication packets)
db_1            | 2021-02-08T22:28:26.294737Z 15 [Note] Aborted connection 15 to db: 'tietokanta' user: 'root' host: '172.20.0.5' (Got an error reading communication packets)
db_1            | 2021-02-08T22:28:26.295162Z 14 [Note] Aborted connection 14 to db: 'tietokanta' user: 'root' host: '172.20.0.5' (Got an error reading communication packets)
db_1            | 2021-02-08T22:28:26.296473Z 0 [Note] Giving 3 client threads a chance to die gracefully
db_1            | 2021-02-08T22:28:26.296630Z 0 [Note] Shutting down slave threads
db_1            | 2021-02-08T22:28:26.296945Z 0 [Note] Event Scheduler: Killing the scheduler thread, thread id 4
db_1            | 2021-02-08T22:28:26.297016Z 0 [Note] Event Scheduler: Waiting for the scheduler thread to reply
db_1            | 2021-02-08T22:28:26.299056Z 0 [Note] Event Scheduler: Stopped
db_1            | 2021-02-08T22:28:26.299225Z 0 [Note] Forcefully disconnecting 0 remaining clients
db_1            | 2021-02-08T22:28:26.299604Z 0 [Note] Event Scheduler: Purging the queue. 0 events
db_1            | 2021-02-08T22:28:26.300339Z 0 [Note] InnoDB: FTS optimize thread exiting.
backend_test_1  | npm ERR! code 143
backend_test_1  | npm ERR! path /opt/app
backend_test_1  | npm ERR! command failed
backend_test_1  | npm ERR! command sh -c nodemon -w src --exec 'npm test'
backend_1       | npm ERR! code 143
backend_1       | npm ERR! path /opt/app
backend_test_1  | 
backend_test_1  | npm ERR! A complete log of this run can be found in:
backend_test_1  | npm ERR!     /root/.npm/_logs/2021-02-08T22_28_26_322Z-debug.log
backend_1       | npm ERR! command failed
backend_1       | npm ERR! command sh -c nodemon src/index.js -w src --exec babel-node
backend_1       | 
backend_1       | npm ERR! A complete log of this run can be found in:
backend_1       | npm ERR!     /root/.npm/_logs/2021-02-08T22_28_26_343Z-debug.log
db_1            | 2021-02-08T22:28:26.405412Z 0 [Note] Binlog end
db_1            | 2021-02-08T22:28:26.420736Z 0 [Note] Shutting down plugin 'ngram'
db_1            | 2021-02-08T22:28:26.420791Z 0 [Note] Shutting down plugin 'BLACKHOLE'
db_1            | 2021-02-08T22:28:26.420798Z 0 [Note] Shutting down plugin 'ARCHIVE'
db_1            | 2021-02-08T22:28:26.420801Z 0 [Note] Shutting down plugin 'INNODB_CACHED_INDEXES'
db_1            | 2021-02-08T22:28:26.420823Z 0 [Note] Shutting down plugin 'INNODB_VIRTUAL'
db_1            | 2021-02-08T22:28:26.420826Z 0 [Note] Shutting down plugin 'INNODB_COLUMNS'
db_1            | 2021-02-08T22:28:26.420828Z 0 [Note] Shutting down plugin 'INNODB_TABLESPACES'
db_1            | 2021-02-08T22:28:26.420831Z 0 [Note] Shutting down plugin 'INNODB_INDEXES'
db_1            | 2021-02-08T22:28:26.420833Z 0 [Note] Shutting down plugin 'INNODB_TABLESTATS'
db_1            | 2021-02-08T22:28:26.420836Z 0 [Note] Shutting down plugin 'INNODB_TABLES'
db_1            | 2021-02-08T22:28:26.420838Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
db_1            | 2021-02-08T22:28:26.420840Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
db_1            | 2021-02-08T22:28:26.420843Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
db_1            | 2021-02-08T22:28:26.420845Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
db_1            | 2021-02-08T22:28:26.420860Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
db_1            | 2021-02-08T22:28:26.420862Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
db_1            | 2021-02-08T22:28:26.420883Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
db_1            | 2021-02-08T22:28:26.420886Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
db_1            | 2021-02-08T22:28:26.420889Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
db_1            | 2021-02-08T22:28:26.420891Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
db_1            | 2021-02-08T22:28:26.420894Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
db_1            | 2021-02-08T22:28:26.420896Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
db_1            | 2021-02-08T22:28:26.420899Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
db_1            | 2021-02-08T22:28:26.420901Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
db_1            | 2021-02-08T22:28:26.420903Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
db_1            | 2021-02-08T22:28:26.420906Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
db_1            | 2021-02-08T22:28:26.420909Z 0 [Note] Shutting down plugin 'INNODB_CMP'
db_1            | 2021-02-08T22:28:26.420911Z 0 [Note] Shutting down plugin 'INNODB_TRX'
db_1            | 2021-02-08T22:28:26.420914Z 0 [Note] Shutting down plugin 'InnoDB'
db_1            | 2021-02-08T22:28:26.421021Z 0 [Note] InnoDB: Starting shutdown...
db_1            | 2021-02-08T22:28:26.521691Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
db_1            | 2021-02-08T22:28:26.522005Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 210208 22:28:26
weather-app_backend_test_1 exited with code 143
weather-app_backend_1 exited with code 143
weather-app_mywebsql_1 exited with code 0
db_1            | 2021-02-08T22:28:27.543662Z 0 [Note] InnoDB: Shutdown completed; log sequence number 26059641
db_1            | 2021-02-08T22:28:27.550843Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
db_1            | 2021-02-08T22:28:27.551064Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
db_1            | 2021-02-08T22:28:27.551090Z 0 [Note] Shutting down plugin 'MyISAM'
db_1            | 2021-02-08T22:28:27.551201Z 0 [Note] Shutting down plugin 'CSV'
db_1            | 2021-02-08T22:28:27.551283Z 0 [Note] Shutting down plugin 'MEMORY'
db_1            | 2021-02-08T22:28:27.551299Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
db_1            | 2021-02-08T22:28:27.551383Z 0 [Note] Shutting down plugin 'TempTable'
db_1            | 2021-02-08T22:28:27.551404Z 0 [Note] Shutting down plugin 'sha2_cache_cleaner'
db_1            | 2021-02-08T22:28:27.551414Z 0 [Note] Shutting down plugin 'caching_sha2_password'
db_1            | 2021-02-08T22:28:27.551425Z 0 [Note] Shutting down plugin 'sha256_password'
db_1            | 2021-02-08T22:28:27.551441Z 0 [Note] Shutting down plugin 'mysql_native_password'
db_1            | 2021-02-08T22:28:27.551595Z 0 [Note] Shutting down plugin 'binlog'
db_1            | 2021-02-08T22:28:27.560449Z 0 [Note] /usr/sbin/mysqld: Shutdown complete
db_1            | 
weather-app_db_1 exited with code 0
Hackintosh:weather-app valtteri$ 
